### ISSUE TITLE
Crash Win 10

### ISSUE THREAD

**Issue by Primula** [EvolutionaryLinguisticsAssociation/Babel2#1]
Error: on #<BASIC-CHARACTER-OUTPUT-STREAM UTF-8 (PIPE/3720) #x210210151D> :
>        Invalid argument during write
> While executing: #<CCL::STANDARD-KERNEL-METHOD CCL::STREAM-IO-ERROR (STREAM T T)>, in process listener(1).

The error above is related to the gnuplot call in the test-babel-installation.lisp file; I use win 10 with CCL and I tried all Babel2 releases on Github. 
Moreover, in the last release (2.0.2) the test-babel-installation.lisp file calls the Q library that does not exist.
Please, help me for installing Babel2 framework asap.

**Comment by JensNevens** [comment]
Hello @Primula 

Thank you for submitting this issue. Concerning the latest release of the Babel2 framework; we have adopted Quicklisp to manage downloading and loading all systems. You can find more information about Quicklisp [here](https://www.quicklisp.org/beta/). Unfortunately, we did not yet update our installation instructions for Windows to reflect this change!

Installing Quicklisp is very easy! First, you download the file `quicklisp.lisp` that is specified on the website linked above. Next, you open up a CCL session and do the following:

```
(load "/path/to/quicklisp.lisp")
(quicklisp-quickstart:install)
```

Also, add the following lines to your `.ccl-init.lisp` file, preferably above the instructions that load Babel2:

```
(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))
```

This should already fix the problem of not being able to load Quicklisp in `test-babel-installation.lisp` in the latest release. Can you already give this a try?

**Comment by Primula** [comment]
I just tried your solution, but the problem persists.


"yes!" To load "web-interface":
  Load 1 ASDF system:
    web-interface
; Loading "web-interface"
> Error: on #<BASIC-CHARACTER-OUTPUT-STREAM UTF-8 (PIPE/4196) #x2101F1726D> :
>        Invalid argument during write
> While executing: #<CCL::STANDARD-KERNEL-METHOD CCL::STREAM-IO-ERROR (STREAM T T)>, in process listener(1).

As shown, the q library seems to well work; the problem is related to the ccl stream with Gnuplot, that is correctly setted in my environment (it separately works): moreover, when ccl interfaces to graphviz it seems to work but the temp "pdf" file is not created in the Babel2/.tmp folder, and the graphviz window does not open.




________________________________
Da: Jens Nevens <notifications@github.com>
Inviato: sabato 27 gennaio 2018 09:12
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Hello @Primula<https://github.com/primula>

Thank you for submitting this issue. Concerning the latest release of the Babel2 framework; we have adopted Quicklisp to manage downloading and loading all systems. You can find more information about Quicklisp here<https://www.quicklisp.org/beta/>. Unfortunately, we did not yet update our installation instructions for Windows to reflect this change!

Installing Quicklisp is very easy! First, you download the file quicklisp.lisp that is specified on the website linked above. Next, you open up a CCL session and do the following:

(load "/path/to/quicklisp.lisp")
(quicklisp-quickstart:install)


Also, add the following lines to your .ccl-init.lisp file, preferably above the instructions that load Babel2:

(let ((quicklisp-init (merge-pathnames "quicklisp/setup.lisp" (user-homedir-pathname))))
  (when (probe-file quicklisp-init)
    (load quicklisp-init)))


This should already fix the problem of not being able to load Quicklisp in test-babel-installation.lisp in the latest release. Can you already give this a try?

**Comment by paulvaneecke** [comment]
Hi @Primula, 

Does the graphviz call underneath work for you? 

`(irl:draw-irl-program '((foo ?a ?b) (bar ?b ?c) (baz ?c ?a)) :open t :format "pdf")`

**Comment by Primula** [comment]
Hi Paul,

I tried the graphviz call before the gnuplot call, and it seems to work but both the pdf file is not created (it is not in Babel2/.tmp directory) and the graphviz window does not open.

I paste above the steps I followed in a CCL session (the ? symbol is the CCL prompt, you know).




* Initializing BABEL.
  The BABEL path is: /Users/annai/Babel2/
Clozure Common Lisp Version 1.11.5/v1.11.5  (WindowsX8664)

For more information about CCL, please see http://ccl.clozure.com.

CCL is free software.  It is distributed under the terms of the Apache
Licence, Version 2.0.
? (in-package :cl-user)
#<Package "COMMON-LISP-USER">
? (print (babel-pathname))

#P"/Users/annai/Babel2/"
#P"/Users/annai/Babel2/"

? (ql:quickload :irl)
To load "irl":
  Load 1 ASDF system:
    irl
; Loading "irl"

(UTILS::test-lists-and-sets): .......................................................................................................
(UTILS::test-tree): ..................
(UTILS::test-misc-utils): .........
(UTILS::test-relation-copying): .......................
(UTILS::test-parent-configurations): ............
 ***** started web interface at http://localhost:8000 *****
.....
(IRL::test-evaluate-primitive): .....
(IRL::test-evaluate-bind-statements): .
(IRL::test-evaluate-primitive-in-program): ..
(IRL::test-evaluate-irl-program): ...........
(IRL::test-equivalent-irl-programs?): .........
(IRL::test-irl-program-connected?): ......
(IRL::test-expand-chunk): ...........
(IRL::test-match-chunk): ................
(IRL::test-binding-helpers): ....................................
(:IRL)
? (progn #+hunchentoot-available-on-this-platform (print "yes!"))

"yes!"
"yes!"
? (ql:quickload :web-interface)
To load "web-interface":
  Load 1 ASDF system:
    web-interface
; Loading "web-interface"

(:WEB-INTERFACE)
? (wi:add-element `((h1) "hello world"))
T
? (irl:draw-irl-program '((foo ?a ?b) (bar ?b ?c) (baz ?c ?a)) :open t :format "pdf")
"/Users/annai/Babel2/.tmp/2018-01-28-17-40-57-graph-1-.pdf"
? (utils:with-open-pipe  (stream (monitors:pipe-to-gnuplot))
  (format stream "plot sin(x)~c" #\newline)
  (finish-output stream))
> Error: on #<BASIC-CHARACTER-OUTPUT-STREAM UTF-8 (PIPE/4240) #x2101E5951D> :
>        Invalid argument during write
> While executing: #<CCL::STANDARD-KERNEL-METHOD CCL::STREAM-IO-ERROR (STREAM T T)>, in process listener(1).



________________________________
Da: Paul Van Eecke <notifications@github.com>
Inviato: domenica 28 gennaio 2018 14:26
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Hi @Primula<https://github.com/primula>,

Does the graphviz call underneath work for you?

(irl:draw-irl-program '((foo ?a ?b) (bar ?b ?c) (baz ?c ?a)) :open t :format "pdf")

**Comment by kbeuls** [comment]
Hello @Primula

We are currently investigating the problem on Windows 10. We will get back to you asap.

**Comment by Primula** [comment]
Hi Katrien,
I wait you.
Regards,
A. P.




________________________________
Da: Katrien Beuls <notifications@github.com>
Inviato: lunedì 29 gennaio 2018 15:23
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Hello @Primula<https://github.com/primula>

We are currently investigating the problem on Windows 10. We will get back to you asap.

**Comment by paulvaneecke** [comment]
Hi @Primula ,

The problems regarding gnuplot and graphviz have been solved now, and should work with the repository version.

Please let us know if you have any further problems.

Best wishes,
Paul

**Comment by Primula** [comment]
Thanks, I try it immediatly!

A.




________________________________
Da: Paul Van Eecke <notifications@github.com>
Inviato: giovedì 1 febbraio 2018 13:13
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Hi @Primula<https://github.com/primula> ,

The problems regarding gnuplot and graphviz have been solved now, and should work with the repository version.

Please let us know if you have any further problems.

Best wishes,
Paul

**Comment by Primula** [comment]
I Paul, I just tried the version and it runs!
But... the web interface is down now :-(
In the previous version it was ok.

A.




________________________________
Da: Arianna Pipitone <annaira77@hotmail.com>
Inviato: giovedì 1 febbraio 2018 13:24
A: EvolutionaryLinguisticsAssociation/Babel2
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Thanks, I try it immediatly!

A.




________________________________
Da: Paul Van Eecke <notifications@github.com>
Inviato: giovedì 1 febbraio 2018 13:13
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Hi @Primula<https://github.com/primula> ,

The problems regarding gnuplot and graphviz have been solved now, and should work with the repository version.

Please let us know if you have any further problems.

Best wishes,
Paul

**Comment by paulvaneecke** [comment]
Okay, thanks for reporting!
I can reproduce the issue and we will look for a solution asap.
(as you can tell, we are not testing on windows often enough - but we will certainly make it work...)

Best,
Paul

**Comment by Primula** [comment]
Paul,

The error seems to be that the server is silent (it does not send data to the browser).

I hope that this can be helpful for you.
A.



________________________________
Da: Paul Van Eecke <notifications@github.com>
Inviato: giovedì 1 febbraio 2018 13:35
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Okay, thanks for reporting!
I can reproduce the issue and we will look for a solution asap.
(as you can tell, we are not testing on windows often enough - but we will certainly make it work...)

Best,
Paul

**Comment by paulvaneecke** [comment]
Hi Primula,

We have solved the problem and updated the repository.

The whole test-babel-installation file should now work. In addition, you can run the following code to test and inspect the (interactive) visualisations in de web interface:

```
(ql:quickload :fcg)
(in-package :fcg)
(activate-monitor trace-fcg)
(load-demo-grammar)
(comprehend-and-formulate "the linguist likes the mouse")
```

Please let us know if this works for you.
Best
Paul

**Comment by Primula** [comment]
Sorry but... it does not work 😞

Gnuplot and graphviz are ok, but the web-interface is down.





________________________________
Da: Paul Van Eecke <notifications@github.com>
Inviato: giovedì 1 febbraio 2018 15:45
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Hi Primula,

We have solved the problem and updated the repository.

The whole test-babel-installation file should now work. In addition, you can run the following code to test and inspect the (interactive) visualisations in de web interface:

(ql:quickload :fcg)
(in-package :fcg)
(activate-monitor trace-fcg)
(load-demo-grammar)
(comprehend-and-formulate "the linguist likes the mouse")


Please let us know if this works for you.
Best
Paul

**Comment by Primula** [comment]
[cid:613b17e7-403b-4e88-baf6-65e7a2af24cd]


Hi Paul!
I found the error; in the "web-interface.lisp" file the #-:windows is actually setted to "localhost", while it has to be "127.0.0.1" as #+:windows.

Update the version and I will try it for you 😊






________________________________
Da: Paul Van Eecke <notifications@github.com>
Inviato: giovedì 1 febbraio 2018 15:45
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


Hi Primula,

We have solved the problem and updated the repository.

The whole test-babel-installation file should now work. In addition, you can run the following code to test and inspect the (interactive) visualisations in de web interface:

(ql:quickload :fcg)
(in-package :fcg)
(activate-monitor trace-fcg)
(load-demo-grammar)
(comprehend-and-formulate "the linguist likes the mouse")


Please let us know if this works for you.
Best
Paul

**Comment by paulvaneecke** [comment]
I'm glad it works for you now. However, I'm a bit puzzled by the solution. The change that I made to make it work was exactly setting the host as "127.0.0.1" on windows. The expression following #-windows should normally just be ignored on windows platforms... 

This could mean ccl does not add `:windows` to `*features*`.
Could you open a lisp, enter `(format t "~s" *features*)` and copy-paste what it prints? This would be really helpful!

**Comment by Primula** [comment]
Hi Paul, here the ccl output of the line you requested


(:HUNCHENTOOT-NO-SSL :HUNCHENTOOT-AVAILABLE-ON-THIS-PLATFORM :QUICKLISP :ASDF-PACKAGE-SYSTEM :ASDF3.1 :ASDF3 :ASDF2 :ASDF :OS-WINDOWS :ASDF-UNICODE :PRIMARY-CLASSES :COMMON-LISP :OPENMCL :CCL :CCL-1.2 :CCL-1.3 :CCL-1.4 :CCL-1.5 :CCL-1.6 :CCL-1.7 :CCL-1.8 :CCL-1.9 :CCL-1.10 :CCL-1.11 :CLOZURE :CLOZURE-COMMON-LISP :ANSI-CL :OPENMCL-UNICODE-STRINGS :IPV6 :OPENMCL-NATIVE-THREADS :OPENMCL-PARTIAL-MOP :MCL-COMMON-MOP-SUBSET :OPENMCL-MOP-2 :OPENMCL-PRIVATE-HASH-TABLES :STATIC-CONSES-SHOULD-WORK-WITH-EGC-IN-CCL :X86-64 :X86_64 :X86-TARGET :X86-HOST :X8664-TARGET :X8664-HOST :WINDOWS-HOST :WINDOWS-TARGET :WIN64-TARGET :WIN64-HOST :64-BIT-TARGET :64-BIT-HOST :WINDOWS :LITTLE-ENDIAN-TARGET :LITTLE-ENDIAN-HOST)
NIL


I see the windows feature, is it?



________________________________
Da: Paul Van Eecke <notifications@github.com>
Inviato: sabato 3 febbraio 2018 12:54
A: EvolutionaryLinguisticsAssociation/Babel2
Cc: Primula; Mention
Oggetto: Re: [EvolutionaryLinguisticsAssociation/Babel2] Crash Win 10 (#1)


I'm glad it works for you now. However, I'm a bit puzzled by the solution. The change that I made to make it work was exactly setting the host as "127.0.0.1" on windows. The expression following #-windows should normally just be ignored on windows platforms...

This could mean ccl does not add :windows to *features*.
Could you open a lisp, enter (format t "~s" *features*) and copy-paste what it prints? This would be really helpful!

**Comment by paulvaneecke** [comment]
Thanks, I'm glad it works for you now :-)
