### ISSUE TITLE
Web server does not seem to start.

### ISSUE THREAD

**Issue by jaccarmac** [EvolutionaryLinguisticsAssociation/Babel2#3]
I've documented my trouble getting the 2.0.6 release to run in SBCL at all. I can get it running in a recent CCL, but the web server does not seem to work. It claims to successfully bind to a port but serves nothing when I visit the address.

**Comment by paulvaneecke** [comment]
On which operating system is this?

**Comment by jaccarmac** [comment]
Linux. I've also checked and the unversioned release from the website seems to work. Not sure what release number it is, the README has a 2016 date in it.

**Comment by paulvaneecke** [comment]
I see, it is possible that the latest version has not been fully tested on linux. Recently, there has been the following problem on windows. In the file `Babel2/systems/web-interface/web-interface.lisp`, the default port was localhost, but on windows, this did not seem to resolve to  127.0.0.1. When specifying it explicitly, it worked. Maybe you could try the same thing on linux (I don't have a linux machine at hand right now)? 

```
(defvar *address* (if (boundp 'cl-user::*web-server-host-address*)
                    (eval 'cl-user::*web-server-host-address*)
                    #+:windows "127.0.0.1" ;; on windows localhost doesn't seem to resolve to 127.0.0.1
                    #-:windows "localhost" 
                    ))
```

**Comment by jaccarmac** [comment]
I used `*web-server-host-address*` instead of changing the file and it worked. Real weird since that variable is bound to "localhost" in the older, working version as well. Thanks for the update, I can take a look at this in Linux in more depth tomorrow.

**Comment by paulvaneecke** [comment]
So you did something like: `defparameter *web-server-host-address* "127.0.0.1"` ?

**Comment by jaccarmac** [comment]
Correct.
