### ISSUE TITLE
Linux install.sh missing - after wget in home_settings

### ISSUE THREAD

**Issue by Ardillen66** [EvolutionaryLinguisticsAssociation/Babel2#5]
In the installation file for linux, this line in the home_settings function: 

(wget -O "https://github.com/EvolutionaryLinguisticsAssociation/Babel2/raw/master/scripts/linux/$NEWFILE" |

is missing the "-" after "wget -O", causing a missing URL error from wget

**Comment by JensNevens** [comment]
Commit ae37c49fb516168f72669c173853745e86db9a0c fixed this issue.
